//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncaTechnologies.Recurrence.Radzen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecurrenceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecurrenceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncaTechnologies.Recurrence.Radzen.RecurrenceStrings", typeof(RecurrenceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        internal static string Inca_At {
            get {
                return ResourceManager.GetString("Inca_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Inca_Day {
            get {
                return ResourceManager.GetString("Inca_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Inca_DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("Inca_DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Inca_DayOfWeek_Monday {
            get {
                return ResourceManager.GetString("Inca_DayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Inca_DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("Inca_DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Inca_DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("Inca_DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Inca_DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("Inca_DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Inca_DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("Inca_DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Inca_DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("Inca_DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string Inca_Every {
            get {
                return ResourceManager.GetString("Inca_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In months.
        /// </summary>
        internal static string Inca_InMonths {
            get {
                return ResourceManager.GetString("Inca_InMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Inca_Month {
            get {
                return ResourceManager.GetString("Inca_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Inca_Month_April {
            get {
                return ResourceManager.GetString("Inca_Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Inca_Month_August {
            get {
                return ResourceManager.GetString("Inca_Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Inca_Month_December {
            get {
                return ResourceManager.GetString("Inca_Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Inca_Month_February {
            get {
                return ResourceManager.GetString("Inca_Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Inca_Month_January {
            get {
                return ResourceManager.GetString("Inca_Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Inca_Month_July {
            get {
                return ResourceManager.GetString("Inca_Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Inca_Month_June {
            get {
                return ResourceManager.GetString("Inca_Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Inca_Month_March {
            get {
                return ResourceManager.GetString("Inca_Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Inca_Month_May {
            get {
                return ResourceManager.GetString("Inca_Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Inca_Month_November {
            get {
                return ResourceManager.GetString("Inca_Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Inca_Month_October {
            get {
                return ResourceManager.GetString("Inca_Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Inca_Month_September {
            get {
                return ResourceManager.GetString("Inca_Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Inca_Number {
            get {
                return ResourceManager.GetString("Inca_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string Inca_Ordinal_First {
            get {
                return ResourceManager.GetString("Inca_Ordinal_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string Inca_Ordinal_Fourth {
            get {
                return ResourceManager.GetString("Inca_Ordinal_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Inca_Ordinal_Last {
            get {
                return ResourceManager.GetString("Inca_Ordinal_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Inca_Ordinal_Second {
            get {
                return ResourceManager.GetString("Inca_Ordinal_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string Inca_Ordinal_Third {
            get {
                return ResourceManager.GetString("Inca_Ordinal_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Inca_Remove {
            get {
                return ResourceManager.GetString("Inca_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify day.
        /// </summary>
        internal static string Inca_SpecifyDay {
            get {
                return ResourceManager.GetString("Inca_SpecifyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify number.
        /// </summary>
        internal static string Inca_SpecifyNumber {
            get {
                return ResourceManager.GetString("Inca_SpecifyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify time.
        /// </summary>
        internal static string Inca_SpecifyTime {
            get {
                return ResourceManager.GetString("Inca_SpecifyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        internal static string Inca_The {
            get {
                return ResourceManager.GetString("Inca_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Inca_Week {
            get {
                return ResourceManager.GetString("Inca_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Inca_Year {
            get {
                return ResourceManager.GetString("Inca_Year", resourceCulture);
            }
        }
    }
}
